version: '3'
services:
  deployment_service:
    image: ghcr.io/eclipse-researchlabs/smartclide-deployment-service:develop
    container_name: deployment_component
    hostname: deployment_component
    ports:
      - 3000:3000   
    environment:
      - GITLAB_URL=https://gitlab.dev.smartclide.eu/
      - MOM_HOST=rabbitmq
      - MOM_PORT=${MOM_PORT}
    links:
      - rabbitmq:rabbitmq
      - mongo:mongo

  rabbitmq:
    image: "rabbitmq:latest"

  mongo:
    image: mongo:latest
    volumes:
      - ./data:/data/db
      
volumes:
  database-data: 