#-------------------------------------------------------------------------------
# Copyright (C) 2021-2022 Wellness TechGroup
# 
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
# 
# SPDX-License-Identifier: EPL-2.0
#-------------------------------------------------------------------------------
version: '3'

services:
  deployment_service:
    build: .
    container_name: deployment_component
    hostname: deployment_component
    ports:
      - 3000:3000
    volumes:
      - ./kube_config:/etc/kubernetes/admin.conf
    
    environment:
      - KUBE_BEARER=${KUBE_BEARER}
      - KUBE_URL=${KUBE_URL}
      - GITLAB_URL=${GITLAB_URL}

      # database:
  #   image: "postgres" 
  #   env_file:
  #     - database.env 
  #   volumes:
  #     - database-data:/var/lib/postgresql/data/ 
  #   ports:
  #     - 5432:5432

  # registry:
  #   image: registry:2
  #   container_name: docker_registry
  #   ports:
  #   - "5000:5000"
  #   environment:
  #     REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
  #   volumes:
  #      - ./data/registry:/data
  #   restart: always
  # jenkins:
  #   image: jenkins/jenkins:lts
  #   privileged: true
  #   user: root
  #   ports:
  #     - 8081:8080
  #     - 50000:50000
  #   container_name: jenkins
  #   volumes:
  #     - ./data/jenkins:/var/jenkins_home
  #     - /home/pberrocal/dev/:/var/jenkins_home/workspace/
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - /usr/local/bin/docker:/usr/local/bin/docker

volumes:
  database-data: 
