version: '3'

services:
  deployment_service:
   build: .
   container_name: deployment_component
   hostname: deployment_component
   ports:
     - 3000:3000   
   environment:
     - GITLAB_URL=${GITLAB_URL}
     - MOM_HOST=${MOM_HOST}
     - MOM_PORT=${MOM_PORT}

  rabbitmq:
    image: "rabbitmq:latest"
    ports:
      - "15672:15672"
      - "5671:5671"
      - "4369:4369"
      - "25672:25672" 
      - "5672:5672" 
      - "15671:15671"

  mongo:
    image: mongo:latest
    hostname: mongo
    container_name: mongo
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017

volumes:
  database-data: 